### PR TITLE
U/danielsf/fix/focal/plane

### PR DESCRIPTION
**Pull request by danielsf**
This pull requests adds data that is used to construct the model of LSST optical distortions.  It consists of PhoSim centroid files representing the positions of objects on the focal plane along with truth catalogs containing the RA, Dec and pupil coordinates of those objects.  There is also data to support unit tests of the model.

### CODE REVIEW

**Review by jbkalmbach — COMMENTED** [review]
This works and I haven't finished the `sims_coordUtils` part of the review yet, but since this is all simulated LSST data anyway, why not just store the computed transformations rather than the data to compute them every time you want to use the cameraUtils code? Is it because if something else changes this data is time consuming to regenerate?

**Comment by danielsf** [comment]
Nominally, `obs_lsstSim` is supposed to reproduce the optical distortions in the r-band.  As of right now, it's not a perfect fit, and I think Simon is intending to update it in the next few months.  By storing the raw data from PhoSim here, we can make sure that what `sims_coordUtils` does is always just an refinement on `obs_lsstSim`, even if `obs_lsstSim` changes beneath us.

**Comment by danielsf** [comment]
I'm pretty sure I've written the `sims_coordUtils` code so that this data will only get read and manipulated the first time you call `focalPlaneCoordsFromPupilCoordsLSST`.  The results will then get cached, so there shouldn't be a lot of overhead.

**Review by jbkalmbach — APPROVED** [review]
Ok, I was thinking it was something related to not wanting to be tied down in case things changed elsewhere. Just wanted to see.

**Pull request merged**
